package entities

import "encoding/json"

// Generated by https://quicktype.io

type OpenWeatherMapAPIErrorResponse struct {
	Code    int    `json:"cod"`
	Message string `json:"message"`
}

func (r *OpenWeatherMapAPIErrorResponse) Error() string {
	val, err := json.Marshal(r)
	if err != nil {
		return r.Message
	}

	return string(val)
}
